## Jenkins Helm values
## Chart: jenkins/jenkins

controller:
  image:
    tag: lts

  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: "1"
      memory: 2Gi

  admin:
    password: "Jenkins12345"

  ingress:
    enabled: true
    ingressClassName: traefik
    hostName: jenkins.homelab.local

  persistence:
    enabled: true
    storageClass: longhorn
    size: 10Gi

  installPlugins:
    - kubernetes:latest
    - workflow-aggregator:latest
    - git:latest
    - configuration-as-code:latest
    - job-dsl:latest

  JCasC:
    configScripts:
      security: |
        unclassified:
          globalJobDslSecurityConfiguration:
            useScriptSecurity: false
      jobs: |
        jobs:
          - script: >
              def managedJobs = []

              managedJobs << 'hello-world'
              pipelineJob('hello-world') {
                description('動作確認用テストジョブ')
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/fukui-yuto/proxmox-lab.git')
                        }
                        branches('*/main')
                      }
                    }
                    scriptPath('k8s/jenkins/jobs/hello-world/Jenkinsfile')
                  }
                }
              }

              managedJobs << 'docker-python'
              pipelineJob('docker-python') {
                description('Dockerfile で Python スクリプトを実行するテストジョブ')
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/fukui-yuto/proxmox-lab.git')
                        }
                        branches('*/main')
                      }
                    }
                    scriptPath('k8s/jenkins/jobs/docker-python/Jenkinsfile')
                  }
                }
              }



              managedJobs << 'go-sample'
              pipelineJob('go-sample') {
                description('Go 動作確認ジョブ')
                definition {
                  cpsScm {
                    scm {
                      git {
                        remote {
                          url('https://github.com/fukui-yuto/proxmox-lab.git')
                        }
                        branches('*/main')
                      }
                    }
                    scriptPath('k8s/jenkins/jobs/go-sample/Jenkinsfile')
                  }
                }
              }
              Jenkins.instance.items.findAll { !(it.name in managedJobs) }.each { it.delete(); println "Deleted: ${it.name}" }

agent:
  resources:
    requests:
      cpu: 50m
      memory: 128Mi
    limits:
      cpu: 512m
      memory: 512Mi
