pipeline {
    agent {
        kubernetes {
            yaml '''
apiVersion: v1
kind: Pod
spec:
  containers:
  - name: kaniko
    image: gcr.io/kaniko-project/executor:debug
    command:
    - sleep
    args:
    - "9999999"
    resources:
      requests:
        cpu: 50m
        memory: 128Mi
      limits:
        cpu: 512m
        memory: 512Mi
'''
        }
    }
    stages {
        stage('Build Docker Image') {
            steps {
                container('kaniko') {
                    sh '''/kaniko/executor \
                        --context dir://$WORKSPACE/k8s/jenkins/jobs/docker-python \
                        --dockerfile $WORKSPACE/k8s/jenkins/jobs/docker-python/Dockerfile \
                        --no-push'''
                }
            }
        }
    }
}
