apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: aiops-step1-alerting
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "11"
spec:
  project: default
  source:
    repoURL: https://github.com/fukui-yuto/proxmox-lab
    targetRevision: HEAD
    path: k8s/aiops/alerting
    directory:
      include: "prometheusrule.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: monitoring
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=false
      - ServerSideApply=true
