apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: harbor
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "5"
spec:
  project: default
  sources:
    - repoURL: https://helm.goharbor.io
      chart: harbor
      targetRevision: "1.14.2"
      helm:
        valueFiles:
          - $values/k8s/harbor/values-harbor.yaml
    - repoURL: https://github.com/fukui-yuto/proxmox-lab
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: harbor
  ignoreDifferences:
    # Harbor Helm chart が初回インストール時にランダム値で生成する Secret は
    # Harbor 自身が更新するため ArgoCD の diff 対象から除外する
    - kind: Secret
      name: harbor-core
      namespace: harbor
      jsonPointers:
        - /data
    - kind: Secret
      name: harbor-jobservice
      namespace: harbor
      jsonPointers:
        - /data
    - kind: Secret
      name: harbor-registry
      namespace: harbor
      jsonPointers:
        - /data
    - kind: Secret
      name: harbor-registry-htpasswd
      namespace: harbor
      jsonPointers:
        - /data
    # harbor Deployment は Helm テンプレートと実際の spec に差分が出るため無視
    - group: apps
      kind: Deployment
      namespace: harbor
      jsonPointers:
        - /spec/template/metadata/annotations
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - RespectIgnoreDifferences=true
