---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-elasticsearch
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://helm.elastic.co
      chart: elasticsearch
      targetRevision: "8.5.1"
      helm:
        valueFiles:
          - $values/k8s/logging/values-elasticsearch.yaml
    - repoURL: https://github.com/fukui-yuto/proxmox-lab
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-fluent-bit
  namespace: argocd
spec:
  project: default
  sources:
    - repoURL: https://fluent.github.io/helm-charts
      chart: fluent-bit
      targetRevision: "0.47.9"
      helm:
        valueFiles:
          - $values/k8s/logging/values-fluent-bit.yaml
    - repoURL: https://github.com/fukui-yuto/proxmox-lab
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: logging-kibana
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/fukui-yuto/proxmox-lab
    targetRevision: HEAD
    path: k8s/logging
    directory:
      include: "kibana.yaml"
  destination:
    server: https://kubernetes.default.svc
    namespace: logging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
