---
# longhorn-prereqs: open-iscsi インストール DaemonSet
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn-prereqs
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/fukui-yuto/proxmox-lab
    targetRevision: HEAD
    path: k8s/longhorn
    directory:
      include: "{namespace.yaml,iscsi-installer.yaml}"
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
---
# longhorn: 分散ブロックストレージ
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: longhorn
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  sources:
    - repoURL: https://charts.longhorn.io
      chart: longhorn
      targetRevision: "1.6.2"
      helm:
        valueFiles:
          - $values/k8s/longhorn/values-longhorn.yaml
    - repoURL: https://github.com/fukui-yuto/proxmox-lab
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: longhorn-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  ignoreDifferences:
    - group: apiextensions.k8s.io
      kind: CustomResourceDefinition
      jsonPointers:
        - /status
